FROM node:16.16.0

WORKDIR /usr/src/app

COPY package.json yarn.lock .yarnrc.yml tsconfig.json ./
COPY .yarn/ ./.yarn

RUN yarn install

COPY . .

RUN yarn build

ENV PORT 8080
EXPOSE ${PORT}

CMD [ "node", "dist/app.js" ]
