name: Publish Weapons API Client to npm

on:
  push:
    branches:
      - main
    paths:
      - "client-packages/weapons/package.json"

  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: "https://registry.npmjs.org/"

      - name: Publish to npm
        run: |
          CURR_VERSION=$(jq -r .version client-packages/weapons/package.json)
          echo "Publishing version $CURR_VERSION to npm"
          npm publish --access public
        working-directory: client-packages/weapons
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
